version: '3.7'

services:

  postgresdb:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./conf/postrgres.env

  django_app:
    build: .
    container_name: django_app
#    volumes:
#      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./conf/app.env
    depends_on:
      - postgresdb

volumes:
  postgres_data: