# Generated by Django 3.2.8 on 2021-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mean_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
