# Generated by Django 3.2.8 on 2021-11-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='Обновление'),
        ),
    ]
